name: Release root
on:
  workflow_dispatch:
    inputs:
      nextVersion:
        description: 'Next development version without "SNAPSHOT". If not provided, the next version will be calculated from the pom'
        required: false
        type: string

jobs:
  pre-release:
    uses: gluonhq/actions/.github/workflows/pre-release.yml@main
  release:
    needs: pre-release
    runs-on: ubuntu-latest
    steps:
      - name: do release
        run: echo "release successful"
  post-release:
    needs: release
    uses: gluonhq/actions/.github/workflows/post-release.yml@main
