name: Release root
on:
  workflow_dispatch:
    inputs:
      nextVersion:
        description: 'Next development version without "SNAPSHOT". If not provided, the next version will be calculated from the pom'
        required: false
        type: string

jobs:
  pre-release:
    uses: gluonhq/actions/.github/workflows/maven-pre-release.yml@v1
  release:
    needs: pre-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 5
          ref: ${{ needs.pre-release.outputs.tag }}
  post-release:
    needs: [pre-release, release]
    uses: gluonhq/actions/.github/workflows/maven-post-release.yml@v1
    with:
      tag: ${{ needs.pre-release.outputs.tag }}
      nextVersion: ${{ github.event.inputs.nextVersion }}
